//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetDescriptionImageApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetDescriptionImageApp.Resources.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        public static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Image Key.
        /// </summary>
        public static string AzureKey {
            get {
                return ResourceManager.GetString("AzureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerimiento de las Imagenes:.
        /// </summary>
        public static string AzureRequirements {
            get {
                return ResourceManager.GetString("AzureRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Translate Key.
        /// </summary>
        public static string AzureTranslateKey {
            get {
                return ResourceManager.GetString("AzureTranslateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box selección imagen para obtener la descripcion.
        /// </summary>
        public static string CheckBoxDescription {
            get {
                return ResourceManager.GetString("CheckBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de la imagen actual:.
        /// </summary>
        public static string CurrentImagePath {
            get {
                return ResourceManager.GetString("CurrentImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción (Alt).
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen del logo de Afaya.
        /// </summary>
        public static string DescriptionLogoAfaya {
            get {
                return ResourceManager.GetString("DescriptionLogoAfaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener Descripciones.
        /// </summary>
        public static string GetDescription {
            get {
                return ResourceManager.GetString("GetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción de la imagen es:.
        /// </summary>
        public static string ImageDescriptionIs {
            get {
                return ResourceManager.GetString("ImageDescriptionIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las dimensiones deben ser mayor a 50 x 50.
        /// </summary>
        public static string ImageDimensionsRequirement {
            get {
                return ResourceManager.GetString("ImageDimensionsRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatos soportados JPG, JPEG, PNG.
        /// </summary>
        public static string ImageFormatRequirement {
            get {
                return ResourceManager.GetString("ImageFormatRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Imagenes.
        /// </summary>
        public static string ImageSelect {
            get {
                return ResourceManager.GetString("ImageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma Descripción.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Máximo Candidatos.
        /// </summary>
        public static string MaxCandidates {
            get {
                return ResourceManager.GetString("MaxCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen debe ser menor a 4Mb.
        /// </summary>
        public static string MaxSizeImageRequirement {
            get {
                return ResourceManager.GetString("MaxSizeImageRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de la Imagen.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Región Azure.
        /// </summary>
        public static string RegionAzure {
            get {
                return ResourceManager.GetString("RegionAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Peticiones Minuto.
        /// </summary>
        public static string RequestAzure {
            get {
                return ResourceManager.GetString("RequestAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma Español.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma Español por traducción.
        /// </summary>
        public static string SpanishTranslate {
            get {
                return ResourceManager.GetString("SpanishTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Description.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar Imagenes.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Image Azure.
        /// </summary>
        public static string UrlAzure {
            get {
                return ResourceManager.GetString("UrlAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Translate Azure.
        /// </summary>
        public static string URLTranslateAzure {
            get {
                return ResourceManager.GetString("URLTranslateAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin descripción.
        /// </summary>
        public static string WithoutDescription {
            get {
                return ResourceManager.GetString("WithoutDescription", resourceCulture);
            }
        }
    }
}
